import { Language } from "./language";
import { Release } from "./release";

// See project.ts for all available parameters
// All of my projects
export const projectDatabase = [
    {
        name: "personal-website",
        title: "Personal Website",
        summary: "My very own website to add everything about myself (the website you are on right now).",
        latestRelease: new Release("0.4.0", "Responsive Design", 1740994926),
        languages: [Language.JavaScript, Language.CSS, Language.TypeScript],
        created: 1723547040,
    },
    {
        name: "database-demo",
        title: "Database Demo",
        summary: "A little database builder.",
        latestRelease: new Release("0.7.1", "Bug Fix", 1734533400),
        languages: [Language.JavaScript, Language.CSS, Language.TypeScript],
        created: 1731950100,
    },
    {
        name: "website-template",
        title: "Website Template",
        summary: "A base template that I use for my websites.",
        latestRelease: new Release("1.3.0", "Header and links improvement", 1739486940),
        languages: [Language.JavaScript, Language.CSS, Language.TypeScript],
        created: 1733346000,
    },
    {
        name: "tic-tac-toe",
        title: "Tic Tac Toe",
        summary: "The famous X and O game, extending greatly from the React tutorial to add other features like bots.",
        latestRelease: new Release("1.0.1", "Bug Fix", 1725207540),
        languages: [Language.JavaScript, Language.CSS, Language.TypeScript],
        created: 1723910640,
    },
    {
        name: "weather-api-experiments",
        title: "Weather API Experiments",
        summary: "A series of experiments to help me get used to the OpenWeather API and using it with Create React App, for an upcoming university project.",
        latestRelease: new Release("1.3.0", "Experiment 3", 1739745300),
        languages: [Language.JavaScript, Language.CSS, Language.HTML, Language.Python],
        isWebsite: false,
        created: 1739446200,
    }, 
    {
        name: "advent-of-code-2024",
        title: "Advent of Code 2024",
        summary: "My solutions to Advent of Code 2024.",
        languages: [Language.Python],
        created: 1734556325,
        isWebsite: false
    },
    {
        name: "little-man-computer",
        title: "Little Man Computer",
        summary: "My A-level 2023 Computer Science Project.",
        latestRelease: new Release("1.1.0", "GitHub Link", 1739817240),
        languages: [Language.JavaScript, Language.CSS, Language.HTML],
        created: 1664409600,
    },
    {
        name: "point-region-quadtree",
        title: "Point Region Quadtree",
        summary: "A showcase of a point region quadtree, the user can click on the canvas to add points and watch it divide.",
        latestRelease: new Release("1.0.0", "Initial Release", 1724300400),
        languages: [Language.JavaScript, Language.CSS],
        created: 1719922811,
    },
    {
        name: "maze-generator",
        title: "Maze Generator",
        summary: "A tool to generate random mazes of different sizes",
        latestRelease: new Release("1.0.0", "Initial Release", 1724295120),
        languages: [Language.JavaScript, Language.HTML, Language.CSS],
        created: 1642377600,
    },
    {
        name: "automata-tool-prototype",
        title: "Automata Tool (Prototype)",
        summary: "A concept for a tool that lets users create Automata, then import/export them.",
        latestRelease: new Release("1.0.0", "Initial Release", 1724293200),
        languages: [Language.JavaScript, Language.HTML, Language.CSS],
        created: 1718929499,
    },
    {
        name: "battleships",
        title: "Battleships",
        summary: "A recreation of the popular board game, made in HTML, JavaScript and CSS.",
        latestRelease: new Release("20/08/24", "Initial Release", 1724139120),
        languages: [Language.JavaScript, Language.HTML, Language.CSS],
        created: 1637452800,
    },
    {
        name: "clock-of-clocks",
        title:  "Clock of Clocks",
        summary: "Website that displays a digital clock made of tiny anologue clocks.",
        latestRelease: new Release("1.0.0", "Initial Release", 1724115420),
        languages: [Language.JavaScript, Language.HTML, Language.CSS],
        created: 1646092800,
    },
    {
        name: "HorseRaceSimulator",
        title: "Horse Race Simulator",
        summary: "A horse race simulator built during my first year of university.",
        latestRelease: new Release("2.0.0", "GUI", 1714162020),
        languages: [Language.Java],
        isPrivate: true,
        isWebsite: false,
        created: 1711505160,
    },
    {
        name: "battleships-two-player",
        title: "Battleships (Two Player)",
        summary: "A two player version of my Battleships project.",
        latestRelease: new Release("13/12/21", "", 1639380720),
        isPrivate: true,
        isWebsite: false,
        languages: [Language.JavaScript, Language.HTML, Language.CSS],
        created: 1639267200,
    },
]